package notes.project.oaut2registration.model;

public enum Scope {
    CHANGE_PASSWORD,
    CHANGE_BLOCKED_STATUS,
    CREATE_ROLE,
    REGISTER_USER,
    GET_USER_STATUS_HISTORY,
    CHANGE_ROLES,
    ANON,
    CHANGE_ROLE_STATUS,
    CHANGE_ROLE_SCOPES,
    GET_SERVICE_CLIENT_HISTORY,
    GET_SERVICE_CLIENTS_LIST
}
