spring:
  datasource:
    type:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
application:
  errorMessages:
    internalError: internal error
    wrongRequestParameters: wrong request parameters

customDataSource:
  serverName: localhost
  databaseName: registration_service
  user: registration_service_user
  password: 1q2w3e